#!/bin/bash -e

###
  #           __                      __             __    _
  #    _____ / /_ _____ __  __ _____ / /_ ___   ____/ /   (_)____
  #   / ___// __// ___// / / // ___// __// _ \ / __  /   / // __ \
  #  (__  )/ /_ / /   / /_/ // /__ / /_ /  __// /_/ /_  / // /_/ /
  # /____/ \__//_/    \__,_/ \___/ \__/ \___/ \__,_/(_)/_/ \____/
  #
  # structed.io - masterless Puppet bootstraper
  # bootstraps new instances for nodeless Puppet
  #
  # normal installation: sh -c "$(curl -s http://con.structed.io/build)"
  # verbose installation: sh -c "$(curl http://con.structed.io/build)" -- -v
  #
  ##


### base config
RANDOM="$(perl -e 'print int(rand(300));')"
TIMESTAMP="$(date -R)"
PUPPET_RPM="http://yum.puppetlabs.com/el/6/products/x86_64/puppetlabs-release-6-7.noarch.rpm"
PUPPET_DIR="${HOME}/.puppet${RANDOM}"
PUPPET_LOCK="${PUPPET_DIR}/puppet-bootstrap.lock"
PUPPET_HOME="/etc/puppet"
FILE_PUPPET_APPLY="${PUPPET_DIR}/puppet-apply.sh"
FILE_PUPPET_RUN="${PUPPET_DIR}/puppet-run.sh"
FILE_PUPPET_UPDATE="${PUPPET_DIR}/puppet-update.sh"
FILE_CRONTAB="${PUPPET_DIR}/puppet-crontab.txt"
FILE_LOG="${PUPPET_DIR}/puppet-bootstrapper.log"
ARGS_CURL="-s"
ARGS_RPM="--quiet --install"
ARGS_YUM="--assumeyes --quiet"


### ad-hoc config
while getopts "v" OPTION
do
  case ${OPTION} in
    v)
      ARGS_CURL="--verbose"
      ARGS_RPM="--install --verbose --hash"
      ARGS_YUM="--assumeyes"
        ;;
  esac
done
### end ad-hoc config


### convience function to echo and log with a single call
echolog()
{
	### check if file exists, is writable and if not: touch it
	if [[ ! -e "${FILE_LOG}" ]]
	then
	  touch "${FILE_LOG}"
	fi


  if [[ -w "${FILE_LOG}" ]]
  then
    echo "${1}"
    echo "[$HOSTNAME] [$(date +'%Y-%m-%dT%H:%M:%S%z')] $@" >> ${FILE_LOG}
  else
    echo "#####"
    echo -e "# You do not have write permissions for \e[0;31m${FILE_LOG}\e[00m, aborting."
    echo "#####"
    exit 1
  fi
}


### check if script is being run as root
if [[ "$(id -u)" != '0' ]]
then
  echo " "
  echo "#####"
  echo -e "# This script must be run as \e[0;31mroot\e[00m, aborting."
  echo "#####"
  echo " "
  exit 1

else
  ### continue if script has not been run before
  if [[ ! -f "${PUPPET_LOCK}" ]]
  then

    clear
    echo " "
    echo "#####"
    echo "# structed.io masterless Puppet bootstrapper"
    echo "#####"
    echo " "

    ### create working directory and switch to it
    mkdir -p ${PUPPET_DIR}
    touch ${FILE_LOG}

    ### this needs to appear after the mkdir, otherwise write perm check fails
    echolog "#1 - creating working directory and switching to it"

    cd ${PUPPET_DIR}


    ### remove any installed versions of Puppet and Puppet Labs release RPM
    echolog "#2 - removing previously installed versions of Puppet"
    yum ${ARGS_YUM} remove puppet > ${FILE_LOG} 2>&1
    yum ${ARGS_YUM} remove puppetlabs-release > ${FILE_LOG} 2>&1


    ### install package for Puppet Labs and clean package database
    echolog "#3 - installing Puppet Labs Release package"
    curl ${ARGS_CURL} --remote-name ${PUPPET_RPM}
    yum ${ARGS_YUM} install puppetlabs-release*.rpm > ${FILE_LOG} 2>&1
    rm ${PUPPET_DIR}/puppetlabs-release*.rpm

    ### install Puppet via package manager
    echolog "#4 - installing Puppet"
    yum ${ARGS_YUM} install puppet > ${FILE_LOG} 2>&1


    ### install dependencies via Puppet
    echolog "#5 - installing core dependencies"
    puppet apply --execute "package { 'crontabs': ensure => 'installed' }"


    ### check if repository have been previously set, see CONSTRUCT-11
    if [[ ! -z "${BOOTSTRAP_REPO}" ]]
    then
      echolog "#6 - Automatically setting repository details"
      echolog "BOOTSTRAP_REPO: ${BOOTSTRAP_REPO}"

      ### stop password from being logged in plain-text
      ###echolog "BOOTSTRAP_PASS: $(for a in `seq ${#BOOTSTRAP_PASS}`; do echo -n '*'; done)"
    else
      ### loop while input is empty or not previously set
      while [[ -z "${BOOTSTRAP_REPO}" ]]
      do
        echolog "#6 - What is the HTTP(s) location of your Puppet manifests?"
        echo "Acceptable format: http(s)://user:pass@structed.io/repository"
        read BOOTSTRAP_REPO
      done
    fi

    # detect repository type by looking at the last three characters of the
    # address; empty responses would indicate that this is not a git repo,
    # so default to svn instead
    BOOTSTRAP_TYPE="${BOOTSTRAP_REPO:${#BOOTSTRAP_REPO} - 3}"

    if [[ "${BOOTSTRAP_TYPE}" != "git" ]]
    then
      BOOTSTRAP_TYPE="subversion"
    fi


    ### install VCS tools
    echo "#7 - installing VCS tools"

    ### use inline Puppet for better OS support, see CONSTRUCT-13, CONSTRUCT-14
    if [[ "${BOOTSTRAP_TYPE}" == "git" ]]
    then
    	puppet apply --execute "package { 'git': ensure => 'installed' }"
    else
    	puppet apply --execute "package { 'subversion': ensure => 'installed' }"
    fi

    ### create Puppet run scripts
    echo "#8 - creating Puppet run scripts"

    ### check if  init script filename has been set or default to safe choice
    if [[ -z "${BOOTSTRAP_INIT}" ]]
    then
      BOOTSTRAP_INIT='init.pp'
    fi

    ### get rid of default Puppet directory
    rm -rf ${PUPPET_HOME}

    ### check out manifests and associated files, see CONSTRUCT-4
    if [[ "${BOOTSTRAP_TYPE}" == "git" ]]
    then
    	### get it all!
    	git clone ${BOOTSTRAP_REPO} ${PUPPET_HOME}
    	git pull
    	git submodule init
    	git submodule update
    else
    	svn co ${BOOTSTRAP_REPO} ${PUPPET_HOME}
    fi

    echo -n "puppet apply /etc/puppet/manifests/${BOOTSTRAP_INIT}" > ${FILE_PUPPET_APPLY}
    echo -n "${PUPPET_DIR}/${FILE_PUPPET_UPDATE}
  ${FILE_PUPPET_APPLY}" > ${FILE_PUPPET_RUN}


    ### create crontab file and add it to crontab
    echolog "#9 - creating crontab"

    echo " " >> ${FILE_CRONTAB}
    echo "# generated by ${0} on ${TIMESTAMP}" >> ${FILE_CRONTAB}

    echo "*/15 * * * * sleep ${RANDOM} && ${FILE_PUPPET_RUN} > /dev/null" > ${FILE_CRONTAB}
    crontab -u ${USER} ${FILE_CRONTAB}


    echolog "#10 - run puppet for the first time"
    echo "sh ${FILE_PUPPET_UPDATE}"
    echo "sh ${FILE_PUPPET_APPLY}"


    ### create lockfile
    echolog "#11 - creating lockfile"
    echo -n "last run: ${TIMESTAMP}" > ${PUPPET_LOCK}
    echo " "


  ### show warning if script has been run before
  else
    echo "#####"
    echolog "#${PUPPET_LOCK} has been found, aborting."
    echo "#####"
  fi # end if for PUPPET_LOCK
fi # end if for root check